/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yushkevich.earthquakes;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.http.HttpClient;
import java.util.Scanner;

public class EarthquakeApplication {

    private static final Logger LOGGER = LoggerFactory.getLogger(EarthquakeApplication.class);

    public static void main(String[] args) {
        var in = new Scanner(System.in);
        System.out.println("Enter lat <ENTER> lon:");
        try {
            var lat = Double.parseDouble(in.next());
            var lon = Double.parseDouble(in.next());

            var httpClient = HttpClient.newBuilder().build();
            var earthquakeRepository = new EarthquakeRepository(httpClient);
            var earthquakeService = new EarthquakeService(earthquakeRepository);

            earthquakeService.getNearestEarthquakes(lat, lon, 10).forEach(System.out::println);
        } catch (NumberFormatException e) {
            LOGGER.error("Two float numbers for lat/lon should be provided", e);
        }
    }
}
